// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("060d39a5-b485-4754-9f47-d2b1b08309bd"),
	Geocodio("3409cd09-e363-4a03-8b47-324d3300b983"),
	LocationIQ("d4c2b60f-3385-45a1-90cd-da3d9922d43e"),
	MapQuest("4905cb01-12f8-4f5d-80cb-cd962bc654a1");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
