// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum Platform
{
	Web("e88955b5-a380-4a26-a275-3b525ac76305"),
	Native_mobile("206eb13e-e088-4f5d-a244-b25deab22faa"),
	Hybrid_mobile("a047c751-b91c-4637-bb41-4fc3583762ea");

	private final java.lang.String i18nCaptionKey;
	
	private Platform(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
