// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("5139a156-2c5b-4a65-bfd6-a0f17b42dc18"),
	startsWith("234e21c2-aa32-4b3c-b9e3-929bb174c7a6"),
	endsWith("855a0424-8099-47b2-bf9c-8a5e8377d3d0"),
	between("7fe18016-2190-4ec0-93b1-1ac49897ac38"),
	greater("275ac7b5-2372-4349-8340-32cf02962fe5"),
	greaterEqual("026a056c-51b0-4894-8276-ce1a8dc1e592"),
	equal("c50ca70b-b841-497a-a74f-543e5271f165"),
	notEqual("d8cf7df8-1eb5-411a-a6b5-6cb81d4390b2"),
	smaller("c401e897-8d0c-43f2-b962-0a592431f433"),
	smallerEqual("32456e81-6f5b-403d-8b7a-a1dffd1473d6"),
	empty("ad6d0136-1675-4ec6-bcf4-2a9efa620d20"),
	notEmpty("c2ef7334-889e-46b5-9104-e461237a1cc4");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
