// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("6555b774-df99-404c-b609-cc259a72ecc1"),
	startsWith("bc1feb67-1ae3-49a5-8ecb-38e18460caba"),
	endsWith("df36b740-fa8d-410a-a378-bcec32d944d9"),
	between("f4b5930d-4d62-4fe1-9922-411091c82f3f"),
	greater("101e74c3-bc71-42cf-99d6-f7996d3c0d0a"),
	greaterEqual("46c0a431-7aa7-4045-8bbd-3cee7f96b191"),
	equal("b55f552b-b686-4089-ad16-ef9b86d27631"),
	notEqual("2d6990d5-dffe-405f-9aee-0de9d5173178"),
	smaller("66c88452-abf8-42f7-bac2-53bb081880ca"),
	smallerEqual("b8bb84e8-74c5-482c-a19a-155f22db8c6b"),
	empty("374dcbba-3321-46ed-bb29-3756dd3049cf"),
	notEmpty("88537d17-9c6a-4971-9a37-f47b34a345ed");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
