// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("d996943c-2178-4a20-b737-4e50831aa709"),
	startsWith("400d631d-5b5b-4a9b-b65d-0232aa415efe"),
	endsWith("67166f0b-6b59-4a91-8edd-c799dded56e7"),
	between("6c18d53b-3174-4c92-a1c9-7f961f3368fd"),
	greater("85c0b0d5-c8d9-4412-8c84-4fd83f9bae7b"),
	greaterEqual("1b74928b-2f25-495d-8c93-a8a1d18e5749"),
	equal("f6573b6d-3d1e-4f4b-a3c2-9a5c1304e86f"),
	notEqual("ae1ba0f9-a62a-4fa7-ad4c-657de36bf869"),
	smaller("98d4089f-f1ce-4095-a363-4b13d37895e1"),
	smallerEqual("a48def46-67aa-4148-b273-ed5aabf2e0f8"),
	empty("a7afd022-d244-46b8-b888-01c7d2cac39f"),
	notEmpty("3ce2cce5-45fe-462a-8f3a-8af63cd9268d");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
