// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("8a51ba4b-15c3-4d4b-abfd-bf8b32ae7641"),
	denied("a5a94dd2-f30e-48e6-97ad-e8c1451b0c13"),
	limited("5208043b-4c3e-44a9-b50d-1346ee4c40ce"),
	granted("a80a8046-1631-4c72-9c36-57bc27868b06"),
	blocked("9159fd96-35b6-4d35-b1b7-54b615d0bbf2");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
