// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("e7edf5c4-cbb7-4429-870e-8d98f44625da"),
	denied("db7f7f47-cc92-43aa-b94f-de67bb63d00a"),
	limited("a7885a0d-a3f9-4278-aec0-aff32460e2d4"),
	granted("f6a6d92a-65a8-4829-8785-acc5707cfb4e"),
	blocked("021f353f-2277-4827-80c6-bd8371afb22d");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
