// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("a7baf6a5-67b1-40c5-afbb-50e3277e1625"),
	denied("a0a99fd3-769a-4f76-9fcb-5975167814ed"),
	limited("7c6f72fb-934c-4303-b491-95cc3b336a89"),
	granted("bf0f464b-35fb-489f-a101-8627b8a8d46a"),
	blocked("ae3999c6-df7e-4679-a6d0-41fc38575132");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
