// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("d11d4f74-db93-4f8f-8c0a-96bb43c5d773"),
	low("e5029819-3380-49c8-aeba-82f0bfd59d5e"),
	medium("87567c8f-5afd-46fc-8e24-948a487132e2"),
	high("d992a79b-a842-4924-abc4-623a4ec70e41"),
	custom("1d1f0016-8ceb-4f22-9922-cf0f8e0651d7");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
