// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("f6a4585f-1e65-4930-8a80-48520b8eb5ea"),
	low("be84e49b-bc7f-4f2b-a5a3-e737423e19fb"),
	medium("8e73a593-4cee-431d-a03b-7b1f138af36b"),
	high("b7aa9b51-3a42-4700-830e-3ba657947502"),
	custom("0060ab84-437e-493f-9d79-8b721c3b63a7");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
